# Generated by Django 4.2.8 on 2025-06-27 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('bio', models.TextField(blank=True, verbose_name='Hakkımda')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='İlçe')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('experience_years', models.PositiveIntegerField(choices=[(0, 'Yeni başlayan'), (1, '1 yıl'), (2, '2 yıl'), (3, '3 yıl'), (4, '4 yıl'), (5, '5 yıl'), (6, '6-10 yıl'), (10, '10+ yıl')], default=0, verbose_name='Deneyim')),
                ('skills', models.TextField(blank=True, help_text='Virgül ile ayırarak yazın', verbose_name='Yetenekler')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('cv_file', models.FileField(blank=True, upload_to='cvs/', verbose_name='CV')),
                ('profile_image', models.ImageField(blank=True, upload_to='profiles/', verbose_name='Profil Fotoğrafı')),
                ('certificates', models.FileField(blank=True, upload_to='certificates/', verbose_name='Sertifikalar')),
                ('is_available', models.BooleanField(default=True, verbose_name='İş Arıyor')),
                ('expected_salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Beklenen Maaş (Min)')),
                ('expected_salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Beklenen Maaş (Max)')),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('successful_applications', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İş Arayan Profili',
                'verbose_name_plural': 'İş Arayan Profilleri',
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=100, verbose_name='Şirket Adı')),
                ('company_description', models.TextField(blank=True, verbose_name='Şirket Açıklaması')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 çalışan'), ('11-50', '11-50 çalışan'), ('51-200', '51-200 çalışan'), ('201-500', '201-500 çalışan'), ('500+', '500+ çalışan')], max_length=20, verbose_name='Şirket Büyüklüğü')),
                ('establishment_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kuruluş Yılı')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='İlçe')),
                ('address', models.TextField(verbose_name='Adres')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='İletişim Kişisi')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='İletişim Telefonu')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulanmış Şirket')),
                ('verification_documents', models.FileField(blank=True, upload_to='verifications/', verbose_name='Doğrulama Belgeleri')),
                ('logo', models.ImageField(blank=True, upload_to='company_logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, upload_to='company_covers/', verbose_name='Kapak Fotoğrafı')),
                ('total_job_posts', models.PositiveIntegerField(default=0)),
                ('active_job_posts', models.PositiveIntegerField(default=0)),
                ('total_applications_received', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İş Veren Profili',
                'verbose_name_plural': 'İş Veren Profilleri',
            },
        ),
    ]
