[phases.setup]
nixPkgs = ["python311", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python manage.py makemigrations messages notifications && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn kuafor_ilan.wsgi:application"
