# Generated by Django 4.2.8 on 2025-07-01 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Plan Adı')),
                ('plan_type', models.CharField(choices=[('free', 'Ücretsiz'), ('basic', 'Temel'), ('pro', 'Profesyonel'), ('enterprise', 'Kurumsal')], max_length=20, unique=True, verbose_name='Plan Tipi')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiyat')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Aylık'), ('quarterly', '3 Aylık'), ('yearly', 'Yıllık')], default='monthly', max_length=20, verbose_name='Faturalama Döngüsü')),
                ('max_job_posts', models.PositiveIntegerField(default=1, verbose_name='Maksimum İlan Sayısı')),
                ('can_highlight_jobs', models.BooleanField(default=False, verbose_name='İlan Öne Çıkarma')),
                ('can_feature_jobs', models.BooleanField(default=False, verbose_name='Öne Çıkan İlan')),
                ('cv_pool_access', models.BooleanField(default=False, verbose_name='CV Havuzu Erişimi')),
                ('priority_support', models.BooleanField(default=False, verbose_name='Öncelikli Destek')),
                ('analytics_access', models.BooleanField(default=False, verbose_name='Analitik Erişimi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Üyelik Planı',
                'verbose_name_plural': 'Üyelik Planları',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('cancelled', 'İptal Edildi'), ('expired', 'Süresi Doldu'), ('suspended', 'Askıya Alındı')], default='active', max_length=20, verbose_name='Durum')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Otomatik Yenileme')),
                ('jobs_posted_this_period', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberships.subscriptionplan', verbose_name='Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Üyeliği',
                'verbose_name_plural': 'Kullanıcı Üyelikleri',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_name', models.CharField(max_length=100, verbose_name='Özellik Adı')),
                ('feature_description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_included', models.BooleanField(default=True, verbose_name='Dahil mi?')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='memberships.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Plan Özelliği',
                'verbose_name_plural': 'Plan Özellikleri',
                'ordering': ['plan', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MembershipUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('price_difference', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('current_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_upgrades', to='memberships.subscriptionplan')),
                ('requested_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_upgrades', to='memberships.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üyelik Yükseltme',
                'verbose_name_plural': 'Üyelik Yükseltmeleri',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Kredi Kartı'), ('bank_transfer', 'Banka Havalesi'), ('iyzico', 'İyzico')], default='iyzico', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('refunded', 'İade Edildi')], default='pending', max_length=20)),
                ('payment_provider_id', models.CharField(blank=True, max_length=200)),
                ('payment_provider_response', models.JSONField(blank=True, default=dict)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='memberships.usermembership')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberships.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üyelik Ödemesi',
                'verbose_name_plural': 'Üyelik Ödemeleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
